### ISSUE TITLE
Need an airflow scheduler for the FX Pricing Service

### ISSUE THREAD

**Issue by bryonbaker** [os-climate/data-platform-demo#54]
The Markets Pricing Service v1.0 is now complete. This needs to be configured to run as a scheduled job in Airflow.

The image is: quay.io/brbaker/market-pricing:v0.5.2
Airflow user-defined environment variables are: BASE, CURRENCIES, DRYRUN, and UPDATEDAFTER

PodSpec is:
```
apiVersion: v1
kind: Pod
metadata:
  name: market-pricing
spec:
  containers:
  - name: market-pricing
    image: quay.io/brbaker/market-pricing:v0.5.2
    command: ["/app/market-pricing-svc"]
    args: ["$(BASE)", "$(CURRENCIES)", "$(UPDATEDAFTER)"]
    imagePullPolicy: Always
    volumeMounts:
    - name: config
      mountPath: "/app/config"
      readOnly: true
    env:
    - name: BASE
      value: "--base-currency=EUR"
    - name: CURRENCIES
      value: "--currencies=AUD,NZD,USD,GBP"
    - name: DRYRUN
      value: "--dry-run"
    - name: UPDATEDAFTER
      value: "--updated-after=2022-01-01"
  restartPolicy: Never
  volumes:
  - name: config
    configMap:
      name: app-config  # Provide the name of the ConfigMap you want to mount.
      items:                  # An array of keys from the ConfigMap to create as files
      - key: "kafka.properties"
        path: "kafka.properties"
      - key: "app-config.properties"
        path: "app-config.properties"
```
